### ISSUE TITLE
fps screen capture/ aim sensitivity

### ISSUE THREAD

**Issue by NewFakeNoxy** [Mvr444/Mvr-s-Softaim#1]
Hello,
tried the code yesterday but i´ve had a few problems which i wanted to discuss. the screen capture is 4fps, i think thats the max it can do but is there a way to "crank it up" drastically so that thee tracking is smoother? becuase right now it flicks onto the enemy but the enemy is already gone because the script is just a few fps behind. nvm i just realised you stole the project.

**Comment by Mvr444** [comment]
You need a Nvidia for more than 4 fps.
You can look at https://github.com/zeyad-mansour/lunar and ask for more information because I stole the project.
